import { Router } from 'express';
import healthRoutes from './health.routes.js';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import roleRoutes from './role.routes.js';
import permissionRoutes from './permission.routes.js';
import settingsRoutes from './settings.routes.js';
import footerRoutes from './footer.routes.js';
import navigationRoutes from './navigation.routes.js';
import socialLinkRoutes from './socialLink.routes.js';
import homepageRoutes from './homepage.routes.js';
import heroBannerRoutes from './heroBanner.routes.js';
import pageContentRoutes from './pageContent.routes.js';
import seoMetaRoutes from './seoMeta.routes.js';
import serviceRoutes from './service.routes.js';
import industryRoutes from './industry.routes.js';
import platformRoutes from './platform.routes.js';
import processStepRoutes from './processStep.routes.js';
import benefitRoutes from './benefit.routes.js';
import statisticRoutes from './statistic.routes.js';
import blogRoutes from './blog.routes.js';
import careerRoutes from './career.routes.js';
import jobApplicationRoutes from './jobApplication.routes.js';
import riderApplicationRoutes from './riderApplication.routes.js';
import testimonialRoutes from './testimonial.routes.js';
import clientRoutes from './client.routes.js';
import portfolioRoutes from './portfolio.routes.js';
import faqRoutes from './faq.routes.js';
import mediaRoutes from './media.routes.js';
import contactRequestRoutes from './contactRequest.routes.js';
import newsletterRoutes from './newsletter.routes.js';
import awardRoutes from './award.routes.js';
import certificateRoutes from './certificate.routes.js';
import officeRoutes from './office.routes.js';
import teamMemberRoutes from './teamMember.routes.js';
import activityLogRoutes from './activityLog.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import notificationRoutes from './notification.routes.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/settings', settingsRoutes);
router.use('/footer', footerRoutes);
router.use('/navigation', navigationRoutes);
router.use('/social-links', socialLinkRoutes);
router.use('/homepage', homepageRoutes);
router.use('/hero-banners', heroBannerRoutes);
router.use('/page-content', pageContentRoutes);
router.use('/seo', seoMetaRoutes);
router.use('/services', serviceRoutes);
router.use('/industries', industryRoutes);
router.use('/platforms', platformRoutes);
router.use('/process-steps', processStepRoutes);
router.use('/benefits', benefitRoutes);
router.use('/statistics', statisticRoutes);
router.use('/blog', blogRoutes);
router.use('/careers', careerRoutes);
router.use('/job-applications', jobApplicationRoutes);
router.use('/rider-applications', riderApplicationRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/clients', clientRoutes);
router.use('/portfolio', portfolioRoutes);
router.use('/faq', faqRoutes);
router.use('/media', mediaRoutes);
router.use('/contact-requests', contactRequestRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/awards', awardRoutes);
router.use('/certificates', certificateRoutes);
router.use('/offices', officeRoutes);
router.use('/team', teamMemberRoutes);
router.use('/activity-logs', activityLogRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/notifications', notificationRoutes);

// Remaining module routers are mounted here one at a time, as each module is built:

export default router;
