import {
  Rocket,
  Zap,
  Clock,
  ShieldCheck,
  TrendingUp,
  Users,
  MapPin,
  Package,
  Truck,
  Bike,
  Car,
  Wallet,
  CreditCard,
  FileCheck,
  Headset,
  Star,
  Award,
  Target,
  Handshake,
  Building2,
  Globe,
  Smartphone,
  Wifi,
  CheckCircle2,
  ThumbsUp,
  Heart,
  Lightbulb,
  Settings,
  Layers,
  BarChart3,
  Calendar,
  Phone,
  Mail,
  Home,
  ShoppingBag,
  UtensilsCrossed,
  Coffee,
  Circle,
} from 'lucide-react';

// A curated, statically-imported set — admin-entered icon names are matched
// case-insensitively against this map. Deliberately not the full ~2000-icon
// dynamic-import catalog: that pulled a 250KB+ shared chunk into every page
// that renders an icon, for a feature (icon pickers on content forms) that
// doesn't need the entire library. Unmapped names fall back to a plain dot.
const ICON_MAP = {
  rocket: Rocket,
  zap: Zap,
  clock: Clock,
  shieldcheck: ShieldCheck,
  shield: ShieldCheck,
  trendingup: TrendingUp,
  users: Users,
  mappin: MapPin,
  location: MapPin,
  package: Package,
  truck: Truck,
  bike: Bike,
  car: Car,
  wallet: Wallet,
  creditcard: CreditCard,
  filecheck: FileCheck,
  headset: Headset,
  support: Headset,
  star: Star,
  award: Award,
  target: Target,
  handshake: Handshake,
  building: Building2,
  building2: Building2,
  globe: Globe,
  smartphone: Smartphone,
  wifi: Wifi,
  checkcircle: CheckCircle2,
  checkcircle2: CheckCircle2,
  thumbsup: ThumbsUp,
  heart: Heart,
  lightbulb: Lightbulb,
  settings: Settings,
  layers: Layers,
  barchart: BarChart3,
  barchart3: BarChart3,
  calendar: Calendar,
  phone: Phone,
  mail: Mail,
  home: Home,
  shoppingbag: ShoppingBag,
  food: UtensilsCrossed,
  utensils: UtensilsCrossed,
  coffee: Coffee,
};

export function DynamicIcon({ name, ...props }) {
  const key = name ? name.replace(/[\s-]/g, '').toLowerCase() : '';
  const Icon = ICON_MAP[key] ?? Circle;
  return <Icon aria-hidden="true" {...props} />;
}
